# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f01787491f00ecddb3c545a0bdab65505a21d7e455859daae35aa3f159227ee05f28eaf95659cd732ae1afd65c42d20aaadad6927b2e48ecbaf53e32d3d3cf75

test:
  secret_key_base: 98ff6132327c29fae476402ba07904e400923a10b2d25f6c0d7e6221480b955ec203b3cd52c2ac611874de09cb59d688ecf28450bfa70173acc1fa350646d9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
